export { keyboards };
let keyboards = [
  {
    name: "7skb",
    layout: ["rev1"],
    keymap: [],
    firmware: "ble_micro_pro",
    split: true,
    lpme: true,
  },
  {
    name: "angel64",
    layout: ["rev1"],
    keymap: [],
    firmware: "ble_micro_pro",
    split: false,
    lpme: false,
  },
  {
    name: "bat43",
    layout: [""],
    keymap: [],
    firmware: "ble_micro_pro",
    split: false,
    lpme: false,
  },
  {
    name: "ble_micro_pro",
    layout: [""],
    keymap: [],
    firmware: "ble_micro_pro",
    split: false,
    lpme: false,
  },
  {
    name: "ble_micro_pro_split",
    layout: [""],
    keymap: [],
    firmware: "ble_micro_pro",
    split: true,
    lpme: true,
  },
  {
    name: "choco60",
    layout: [""],
    keymap: [],
    firmware: "ble_micro_pro",
    split: true,
    lpme: true,
  },
  {
    name: "claw44",
    layout: ["rev1"],
    keymap: [],
    firmware: "ble_micro_pro",
    split: true,
    lpme: true,
  },
  {
    name: "cocoa40",
    layout: [""],
    keymap: [],
    firmware: "ble_micro_pro",
    split: true,
    lpme: true,
  },
  {
    name: "crkbd",
    layout: ["rev1"],
    keymap: [],
    firmware: "ble_micro_pro",
    split: true,
    lpme: true,
  },
  {
    name: "crkbd_ecwl",
    layout: [""],
    keymap: [],
    firmware: "crkbd_ecwl",
    split: true,
    lpme: false,
  },
  {
    name: "dozen0",
    layout: [""],
    keymap: [],
    firmware: "ble_micro_pro",
    split: false,
    lpme: false,
  },
  {
    name: "ergo42",
    layout: ["rev1_layout_ortho_4x14"],
    keymap: [],
    firmware: "ble_micro_pro",
    split: true,
    lpme: true,
  },
  {
    name: "ergodash",
    layout: [
      "rev1_layout_2key",
      "rev1_layout_3key_1us",
      "rev1_layout_3key_2us",
      "rev1_layout_4key",
      "rev1_layout_4key_2u_inner",
    ],
    keymap: [],
    firmware: "ble_micro_pro",
    split: true,
    lpme: true,
  },
  {
    name: "ergodash_mini",
    layout: [""],
    keymap: [],
    firmware: "ble_micro_pro",
    split: true,
    lpme: true,
  },
  {
    name: "helix",
    layout: ["5row"],
    keymap: [],
    firmware: "ble_micro_pro",
    split: true,
    lpme: true,
  },
  {
    name: "jisplit89",
    layout: ["rev1"],
    keymap: [],
    firmware: "ble_micro_pro",
    split: true,
    lpme: false,
  },
  {
    name: "keyboard_quantizer",
    layout: [""],
    keymap: [],
    firmware: "keyboard_quantizer",
    split: false,
    lpme: false,
  },
  {
    name: "kugel",
    layout: [""],
    keymap: [],
    firmware: "kugel",
    split: false,
    lpme: false,
  },
  {
    name: "leftover30",
    layout: ["default"],
    keymap: [],
    firmware: "ble_micro_pro",
    split: false,
    lpme: false,
  },
  {
    name: "lets_split",
    layout: ["rev2"],
    keymap: [],
    firmware: "ble_micro_pro",
    split: true,
    lpme: false,
  },
  {
    name: "lily58",
    layout: ["rev1"],
    keymap: [],
    firmware: "ble_micro_pro",
    split: true,
    lpme: true,
  },
  {
    name: "mint60",
    layout: [""],
    keymap: [],
    firmware: "ble_micro_pro",
    split: true,
    lpme: true,
  },
  {
    name: "naked48",
    layout: ["rev1"],
    keymap: [],
    firmware: "ble_micro_pro",
    split: false,
    lpme: false,
  },
  {
    name: "naked60",
    layout: ["rev1"],
    keymap: [],
    firmware: "ble_micro_pro",
    split: false,
    lpme: false,
  },
  {
    name: "naked64",
    layout: ["rev1"],
    keymap: [],
    firmware: "ble_micro_pro",
    split: false,
    lpme: false,
  },
  {
    name: "nomu30",
    layout: [""],
    keymap: [],
    firmware: "ble_micro_pro",
    split: false,
    lpme: false,
  },
  {
    name: "numatreus",
    layout: [""],
    keymap: [],
    firmware: "ble_micro_pro",
    split: false,
    lpme: false,
  },
  {
    name: "otaku_split",
    layout: ["rev1"],
    keymap: [],
    firmware: "ble_micro_pro",
    split: true,
    lpme: true,
  },
  {
    name: "rect44",
    layout: [""],
    keymap: [],
    firmware: "ble_micro_pro",
    split: false,
    lpme: false,
  },
  {
    name: "runner3680",
    layout: ["3x6", "3x7", "3x8", "4x6", "4x7", "4x8", "5x6", "5x7", "5x8"],
    keymap: [],
    firmware: "ble_micro_pro",
    split: true,
    lpme: true,
  },
  {
    name: "toybox",
    layout: [""],
    keymap: [],
    firmware: "toybox",
    split: true,
    lpme: false,
  },
  {
    name: "toybox_single",
    layout: [""],
    keymap: [],
    firmware: "toybox",
    split: false,
    lpme: false,
  },
  {
    name: "treadstone48",
    layout: [
      "rev1_layout_base_default",
      "rev2_layout_base_default",
      "rev2_layout_base_marksard",
    ],
    keymap: [],
    firmware: "ble_micro_pro",
    split: false,
    lpme: false,
  },
  {
    name: "uzu42",
    layout: ["rev1"],
    keymap: [],
    firmware: "ble_micro_pro",
    split: true,
    lpme: true,
  },
  {
    name: "zinc",
    layout: ["rev1"],
    keymap: [],
    firmware: "ble_micro_pro",
    split: true,
    lpme: true,
  },
];
